# -*- coding: utf-8 -*-
required_fields = {
    "UnidadGeologica": {
        "EON": 1,
        "ERA": 2,
        "PERIODO": 3,
        "EPOCA": 4,
        "EDAD": 5,
        "NOMBRE": "DefaultNombre",
        "NOMENCLAT": "DefaultNomenclatura"
    },
    "UnidadPaisaje": {
        "NOMBRE": "DefaultNombre",
        "NOMENCLAT": "DefaultNomenclatura",
        "ESC_VIS": 1,
        "N_INTERES": 2,
        "EL_DISC": 0,
        "TA_DISC": 0,
        "CORR_CROM": 0,
        "CALID_VISU": 1,
        "FRAGI_VISU": 1,
        "INTEG_ESCE": 1,
        "DES_INTEG": "DefaultDescripción",
        "OBSERV": "DefaultObservaciones",
        "AREA_ha": 0
    },
    "CuencaHidrografica": {
        "AH": "DefaultAH",
        "ZH": "DefaultZH",
        "SZH": "DefaultSZH",
        "N_MIC_CUE": "DefaultMicrocuenca",
        "C_MIC_CUE": "DefaultCódigoMicrocuenca",
        "NOMBRE": "DefaultNombre",
        "NOMENCLAT": "DefaultNomenclatura",
        "OBSERV": "DefaultObservaciones",
        "AREA_ha": 0
    },
    "CaptacionAguaSuperPT": {
        "OPERADOR": "DefaultOperador",
        "PROYECTO": "DefaultProyecto",
        "NUM_ACT_AD": "DefaultNumActAd",
        "FEC_ACT_AD": "1900-01-01",
        "ART_ACT_AD": "DefaultArtActAd",
        "ID_PREDIO": "DefaultIDPredio",
        "MAT_INMOB": "DefaultMatInmob",
        "NOM_PROPIE": "DefaultNomProp",
        "HORAS_DIA": 0,
        "DIAS_MES": 0,
        "MES_ANO": 0,
        "U_APROV_1": 1,
        "D_U_APR_1": 0,
        "U_APROV_2": 0,
        "D_U_APR_2": 0,
        "U_APROV_3": 0,
        "D_U_APR_3": 0,
        "U_APROV_4": 0,
        "D_U_APR_4": 0,
        "D_USO_TOT": 0,
        "AH": "DefaultAH",
        "ZH": "DefaultZH",
        "SZH": "DefaultSZH",
        "N_NV_SUB": "DefaultNivelSubsiguiente",
        "C_NV_SUB": "DefaultCódigoNivelSubsiguiente",
        "N_MIC_CUE": "DefaultMicrocuenca",
        "COTA": 0,
        "COOR_ESTE": 0,
        "COOR_NORTE": 0,
        "OBSERV": "DefaultObservaciones"
    },
    "Suelo": {
        "SIMB_U_CAR": "DefaultSimbUCar",
        "TIPO_UN_CA": 1,
        "PISO_TERM": 1,
        "PROV_HUM": 1,
        "RES_TAX_UC": "DefaultResTaxUC",
        "OBSERV": "DefaultObservaciones",
        "AREA_ha": 0
    },
    "PuntoMuestreoFlora": {
        "OPERADOR": "DefaultOperador",
        "PROYECTO": "DefaultProyecto",
        "HABITAT": "DefaultHabitat",
        "DESCRIP": "DefaultDescripción",
        "FEC_MUEST": "1900-01-01",
        "ESTACIONAL": 1,
        "COTA_MIN": 0,
        "COTA_MAX": 0,
        "LONGITUD_m": 0,
        "OBSERV": "DefaultObservaciones"
    },
    "AprovechaForestalPG": {
        "OPERADOR": "DefaultOperador",
        "PROYECTO": "DefaultProyecto",
        "NOMB_A_APR": "DefaultNombre",
        "N3_COBERT": 1,
        "N4_COBERT": 0,
        "N5_COBERT": 0,
        "N6_COBERT": 0,
        "NOMENCLAT": "DefaultNomenclatura",
        "OBSERV": "DefaultObservaciones",
        "AREA_ha": 0
    },
    "Predios": {
        "ID_PREDIO": "DefaultIDPredio",
        "VEREDA": "DefaultVereda",
        "MUNICIPIO": "DefaultMunicipio",
        "DEPTO": "DefaultDepartamento",
        "OBSERV": "DefaultObservaciones",
        "AREA_ha": 0
    },
    "PoblacionReasentar": {
        "NOMBRE": "DefaultNombre",
        "TIPO_ASENT": 1,
        "NOM_U_TERR": "DefaultNivelTerritorial",
        "MUNICIPIO": "DefaultMunicipio",
        "DEPTO": "DefaultDepartamento",
        "OBSERV": "DefaultObservaciones",
        "AREA_ha": 0
    },
    "PoblacionReceptora": {
        "NOMBRE": "DefaultNombre",
        "TIPO_ASENT": 1,
        "NOM_U_TERR": "DefaultNivelTerritorial",
        "MUNICIPIO": "DefaultMunicipio",
        "DEPTO": "DefaultDepartamento",
        "OBSERV": "DefaultObservaciones",
        "AREA_ha": 0
    },
    "CompensacionBiodiversidad": {
        "OPERADOR": "DefaultOperador",
        "PROYECTO": "DefaultProyecto",
        "ID_COMP": "DefaultIDComp",
        "NO_ACTOAD": 1,
        "FE_ACTOAD": "1900-01-01",
        "T_ACTO_OBL": 1,
        "RES_OBL": 1,
        "FE_OBL": "1900-01-01",
        "AREA_COMP": 0,
        "ACT_COMP": 1,
        "SBACT_COMP": 1,
        "OBSERV": "DefaultObservaciones"
    },
    "OtraCompensacion": {
        "OPERADOR": "DefaultOperador",
        "PROYECTO": "DefaultProyecto",
        "ID_OT_COMP": "DefaultIDComp",
        "NO_ACTOAD": 1,
        "FE_ACTOAD": "1900-01-01",
        "T_ACTO_OBL": 1,
        "RES_OBL": 1,
        "FE_OBL": "1900-01-01",
        "AREA_COMP": 0,
        "ACTIVIDAD": 1,
        "OTRA_ACT": "DefaultOtraAct",
        "DESCRIPCIO": "DefaultDescripción",
        "AREA_PG_ha": 0
    }
}

